<a href="https://colab.research.google.com/github/AqueeqAzam/a-deep-dive-introduction-to-tensorflow/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# `Tensorflow version`

In [ ]:
import tensorflow as tf
print(tf.__version__)


2.15.0


# `Creating Scaler`

In [ ]:
import tensorflow as tf
scaler = tf.constant(7)
scaler

# changable tensor
# This class is used to define tensors that can be updated during training or computations.
# Weights and biases in neural networks are typically variables that get adjusted during training.
change_tensor = tf.Variable([10, 4])

# Their values cannot be changed after creation. Defining fixed weights and biases in neural networks.
# Avoid accidental modifications during training.
unchange_tensor = tf.constant([10, 4])
change_tensor, unchange_tensor

# assign value
change_tensor[0].assign(7)
change_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 4], dtype=int32)>

# `Creating vector`

In [ ]:
import tensorflow as tf

# Constant 1-D Tensor from a python list.

vector = tf.constant([10, 20, 78, 89])
vector

# check dimension
vector.ndim

1

# `Create matrix`

A two-dimensional rectangular array of numbers, arranged in rows and columns.

Linear algebra, solving systems of equations, representing geometric transformations, image processing (when using pixel intensities).

In [ ]:
import tensorflow as tf
matrix = tf.constant([[12, 5],
                      [45, 3]])
matrix

matrix.ndim

2

# `Create tensor`

 A generalization of matrices. They can be multi-dimensional arrays of any data type (numbers, strings, booleans, etc.).

 Deep learning, machine learning, signal processing, scientific computing (where multi-dimensional data is common).

In [ ]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9],
                       [10, 11, 12],
                       [13, 14, 15]]])
tensor
tensor.ndim
tensor.shape
tensor.dtype


TensorShape([1, 5, 3])

# `Create random tensor`

In [ ]:
import tensorflow as tf

# Create a generator object with seed 10
random_1 = tf.random.Generator.from_seed(42)

# Generate some random numbers
random_1 = random_1.normal(shape=(3, 2))
random_1

random_2 = tf.random.Generator.from_seed(32)
random_2 = random_2.normal(shape=(3, 2))
random_2

# check equality
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.7901182,  1.585549 ],
       [ 0.4356279,  0.2364518],
       [-0.1589871,  1.302304 ]], dtype=float32)>

# `Shuffle the order`

In [ ]:
import tensorflow as tf

not_suffled = tf.constant([[10, 4],
                           [12, 5]])
not_suffled

suffled = tf.random.shuffle(not_suffled)
suffled

# random result
tf.random.shuffle(not_suffled, seed=42)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  5],
       [10,  4]], dtype=int32)>

# `Other ways to create tensor`

In [ ]:
import tensorflow as tf

# for 1-dim
tf.zeros(2)
tf.ones(5)

# for n-dim
tf.zeros([10, 4])
tf.ones([12, 3])

# `Turn numpy array to tensor`

tensor run much faster then numpy array

In [ ]:
import numpy as np
import tensorflow as tf

numpy_A = np.arange(1, 7, dtype=np.int32) # Changed the range to have 6 elements
numpy_A

# change into tensor
change_tensor = tf.constant(numpy_A)
change_tensor

# change into tensor with shape
change_tensor = tf.constant(numpy_A, shape=(2, 3)) # Now the shape is compatible
change_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

# `Getting info from tensor`

In [ ]:
import tensorflow as tf

# creating rank 4 tesnor (4-dim array)
rank_tensor = tf.zeros([1, 2, 3, 4])

rank_tensor

# Datatype of every elements
rank_tensor.dtype

# Shape of tensor
rank_tensor.shape

# Dimension of tensor (rank)
rank_tensor.ndim

# Total number of elemenst in tensor
tf.size(rank_tensor)

# Elements along 0 axis
rank_tensor.shape[0]


1

# `Indexing tensor`

In [ ]:
import tensorflow as tf

tensor_list = [1, 2, 3, 4]

# Convert the list to a tensor:
tensor = tf.constant(tensor_list)
tensor

# Get the first 2 elements from the tensor:
first_two = tensor[:2]
first_two

# Get the last 2 elements from the tensor:
last_two = tensor[2:]
last_two

# Get every other element from the tensor:
every_other = tensor[::2]
every_other

# Reverse the tensor:
reversed_tensor = tensor[::-1]
reversed_tensor
# Now you can slice the tensor:
result = tensor[:2]
print(result)

tf.Tensor([1 2], shape=(2,), dtype=int32)


# `Basic Operations`

In [ ]:
import tensorflow as tf

tensor = tf.constant([[10, 7], [3, 4]], dtype=tf.float32)
add = tensor + 10
add

# alternative
tf.math.add(tensor, 10)

tf.math.add(25,4)

sub = tensor - 10
sub

mul = tensor * 10
mul

div = tensor / 10
div

mod = tensor % 10
mod

exp = tensor ** 0
exp

exp = tf.math.exp(tensor, 2)
exp

log = tf.math.log(tensor, 2)
log

# find square
sqrt = tf.math.sqrt(tensor, 2)
sqrt

# find range
ran = tf.range(1, 10)
ran

# find square root
sqrt_root = tf.math.sqrt(tf.cast(ran, dtype=tf.float32))
sqrt_root


<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

# `Default Datatypes`

In [ ]:
import tensorflow as tf

d_f = tf.constant([1.5, 7.3])
d_f.dtype

d_r = tf.constant([4, 10])
d_r.dtype

# change float32 to float16

d_f = tf.cast(d_f, dtype=tf.float16)
d_f



<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.5, 7.3], dtype=float16)>

# `Arranging tensor`

In [ ]:
import tensorflow as tf
import numpy as np

# get abs value
a = tf.constant([-1, -7])
a_v = tf.abs(a)
a_v

# create random tensor between 0 to 100 of size 50
random_tensor = tf.constant(np.random.randint(0, 100, size=50))
random_tensor

# find size
tf.size(random_tensor)
random_tensor.size

# find shape
tf.shape(random_tensor)
random_tensor.shape

# find dimension
random_tensor.ndim

# find min
tf.reduce_min(random_tensor)

# find max
tf.reduce_max(random_tensor)

# find mean
tf.reduce_mean(random_tensor)

# find sum
tf.reduce_sum(random_tensor)

# find standard deviation
tf.math.reduce_std(random_tensor)

# find variance
tf.math.reduce_variance(random_tensor)

TensorShape([50])

# `Tensor troubleshooting`

In [ ]:
import tensorflow_probability as tfp

# find variance of tensor
tfp.stats.variance(random_tensor)

# find standard deviation
std_dev = tf.math.reduce_std(tf.cast(random_tensor, dtype=tf.float32))
std_dev

# find variance
var = tf.math.reduce_variance(tf.cast(random_tensor, dtype=tf.float32))
var

# find positional min and max
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

# find postional max
tf.argmax(random_tensor)

# find postional min
tf.argmin(random_tensor)



# `Squeezing tensor`

In [ ]:
import tensorflow as tf

G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 50))
G

# `One Hot Encoding`

In [ ]:
import tensorstore as ts
import tensorflow as tf

some_list = [0, 1, 2, 3] # could red, green, blue, purple

tf.one_hot(some_list, depth=4)

# specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="I like tensorflow", off_value="for deep learning")


# `Tensor and Numpy`

In [ ]:
import tensorflow as tf
import numpy as np

T = tf.constant(np.array([1, 2, 3, 4, 5]))
T

# convert tenosr T to numpy array
N = T.numpy(), type(T.numpy())
N

(array([1, 2, 3, 4, 5]), numpy.ndarray)

# Have a nice day